/**
 * E2E: Lifecycle contract tests — data flow between brief → plan → implement.
 *
 * Validates that the data contracts between packages hold with realistic
 * fixture content. Uses real filesystem operations and the actual parsers
 * (not mocks). No Claude invocation — these are structural contract tests.
 *
 * Always runs in CI (no hasCredentials gate).
 */
import { createHash } from 'node:crypto';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, describe, expect, it } from 'vitest';

import {
  checkApprovalStatus,
  parsePlanFile,
  toSyntheticTicket,
} from '@chief-clancy/dev';

import {
  DEFAULT_PLAN,
  writeApprovalMarker,
  writePlanFile,
} from '../helpers/local-plan-setup.js';

// ─── Temp dir management ────────────────────────────────────────────────────

let tempDir: string | undefined;

function createTempDir(): string {
  tempDir = mkdtempSync(join(tmpdir(), 'clancy-contract-'));
  return tempDir;
}

afterEach(() => {
  if (tempDir) {
    rmSync(tempDir, { recursive: true, force: true });
    tempDir = undefined;
  }
});

// ─── Fixtures ───────────────────────────────────────────────────────────────

const BOARD_MODE_PLAN = `## Clancy Implementation Plan

**Ticket:** [PROJ-42] Add dark mode support
**Planned:** 2026-04-13

### Summary

Enable system-wide dark mode toggle in settings.

### Affected Files

| File | Change Type | Description |
| --- | --- | --- |
| \`src/theme.ts\` | Modify | Add dark palette |

### Implementation Approach

Use CSS custom properties for theme switching.

### Test Strategy

- [ ] Verify toggle persists across sessions

### Acceptance Criteria

- [ ] Dark mode toggle visible in settings

### Dependencies

None

### Risks / Considerations

None identified.

### Size Estimate

**M** — Moderate: theme system + toggle

---

_Generated by [Clancy](https://github.com/Pushedskydiver/chief-clancy). To request changes: comment on this ticket, then re-run \`/clancy:plan\` to revise._`;

const PLAN_WITH_FEEDBACK = `## Clancy Implementation Plan

**Source:** .clancy/briefs/test.md
**Row:** #2 — Improved error handling
**Planned:** 2026-04-13

### Summary

Add better error handling to the API layer.

## Feedback

> The previous plan didn't handle timeout errors.

### Changes From Previous Plan

- Added timeout error handling to the fetch layer

### Affected Files

| File | Change Type | Description |
| --- | --- | --- |
| \`src/api.ts\` | Modify | Add timeout handling |

### Implementation Approach

Wrap fetch calls with AbortController.

### Test Strategy

- [ ] Test timeout scenarios

### Acceptance Criteria

- [ ] Timeout errors show user-friendly messages

### Dependencies

None

### Risks / Considerations

None identified.

### Size Estimate

**S** — Small
`;

// ─── Plan → Parser contract ─────────────────────────────────────────────────

describe('Lifecycle contract — plan parser', () => {
  it('parses local-mode plan with all sections', () => {
    const plan = parsePlanFile(DEFAULT_PLAN, 'test-plan-1');

    expect(plan.headerFormat).toBe('local');
    expect(plan.key).toBe('test-plan-1');
    expect(plan.title).toBe('Test feature implementation');
    expect(plan.summary).toContain('Implement the test feature');
    expect(plan.affectedFiles).toContain('src/feature.ts');
    expect(plan.approach).toContain('Create the feature module with TDD');
    expect(plan.testStrategy).toContain('Unit tests for the feature module');
    expect(plan.acceptance).toContain('Feature module exists and is tested');
    expect(plan.size).toBe('S');
    expect(plan.planned).toBe('2026-04-13');
  });

  it('parses board-mode plan with ticket key', () => {
    const plan = parsePlanFile(BOARD_MODE_PLAN, 'ignored-slug');

    expect(plan.headerFormat).toBe('board');
    expect(plan.key).toBe('PROJ-42');
    expect(plan.title).toBe('Add dark mode support');
  });

  it('handles Feedback and Changes sections without breaking', () => {
    const plan = parsePlanFile(PLAN_WITH_FEEDBACK, 'feedback-plan');

    expect(plan.key).toBe('feedback-plan');
    expect(plan.title).toBe('Improved error handling');
    expect(plan.summary).toContain(
      'Add better error handling to the API layer',
    );
    expect(plan.affectedFiles).toContain('src/api.ts');
    expect(plan.approach).toContain('Wrap fetch calls with AbortController');
  });
});

// ─── Plan → Approve contract ────────────────────────────────────────────────

describe('Lifecycle contract — approval marker', () => {
  it('writes marker with correct SHA-256 and timestamp', () => {
    const dir = createTempDir();
    const planPath = writePlanFile(dir, 'approve-test', DEFAULT_PLAN);
    const markerPath = writeApprovalMarker(planPath, DEFAULT_PLAN);

    const marker = readFileSync(markerPath, 'utf8');
    const expectedSha = createHash('sha256').update(DEFAULT_PLAN).digest('hex');

    expect(marker).toContain(`sha256=${expectedSha}`);
    expect(marker).toContain('approved_at=');
  });

  it('checkApprovalStatus returns approved for matching SHA', () => {
    const dir = createTempDir();
    const planPath = writePlanFile(dir, 'sha-match', DEFAULT_PLAN);
    writeApprovalMarker(planPath, DEFAULT_PLAN);

    const fs = {
      readFile: (p: string) => readFileSync(p, 'utf8'),
      exists: (p: string) => {
        try {
          readFileSync(p);
          return true;
        } catch {
          return false;
        }
      },
    };

    const status = checkApprovalStatus(planPath, DEFAULT_PLAN, fs);

    expect(status.status).toBe('approved');
  });

  it('checkApprovalStatus returns modified for SHA mismatch', () => {
    const dir = createTempDir();
    const planPath = writePlanFile(dir, 'sha-mismatch', DEFAULT_PLAN);
    writeApprovalMarker(planPath, DEFAULT_PLAN);

    const modifiedContent = DEFAULT_PLAN + '\n<!-- edited after approval -->';
    writeFileSync(planPath, modifiedContent, 'utf8');

    const fs = {
      readFile: (p: string) => readFileSync(p, 'utf8'),
      exists: (p: string) => {
        try {
          readFileSync(p);
          return true;
        } catch {
          return false;
        }
      },
    };

    const status = checkApprovalStatus(planPath, modifiedContent, fs);

    expect(status.status).toBe('modified');
  });

  it('checkApprovalStatus returns not-approved when marker is missing', () => {
    const dir = createTempDir();
    const planPath = writePlanFile(dir, 'no-marker', DEFAULT_PLAN);

    const fs = {
      readFile: (p: string) => readFileSync(p, 'utf8'),
      exists: (p: string) => {
        try {
          readFileSync(p);
          return true;
        } catch {
          return false;
        }
      },
    };

    const status = checkApprovalStatus(planPath, DEFAULT_PLAN, fs);

    expect(status.status).toBe('not-approved');
  });
});

// ─── Plan → Implement contract ──────────────────────────────────────────────

describe('Lifecycle contract — synthetic ticket', () => {
  it('maps local-mode plan to synthetic ticket with correct fields', () => {
    const plan = parsePlanFile(DEFAULT_PLAN, 'my-feature-1');
    const ticket = toSyntheticTicket(plan);

    expect(ticket.key).toBe('my-feature-1');
    expect(ticket.title).toBe('Test feature implementation');
    expect(ticket.description).toContain('test feature');
    expect(ticket.description).toContain('src/feature.ts');
    expect(ticket.description).toContain('TDD');
    expect(ticket.parentInfo).toBe('none');
    expect(ticket.blockers).toBe('None');
  });

  it('maps board-mode plan to synthetic ticket with ticket key', () => {
    const plan = parsePlanFile(BOARD_MODE_PLAN, 'ignored');
    const ticket = toSyntheticTicket(plan);

    expect(ticket.key).toBe('PROJ-42');
    expect(ticket.title).toBe('Add dark mode support');
  });

  it('includes all content sections in description', () => {
    const plan = parsePlanFile(DEFAULT_PLAN, 'content-check');
    const ticket = toSyntheticTicket(plan);

    // description = summary + affectedFiles + approach + testStrategy + acceptance
    expect(ticket.description).toContain('Implement the test feature');
    expect(ticket.description).toContain('src/feature.ts');
    expect(ticket.description).toContain('Create the feature module');
    expect(ticket.description).toContain('Unit tests');
    expect(ticket.description).toContain('Feature module exists');
  });
});
