/**
 * Plan file parser for `--from` mode.
 *
 * Parses both board-mode (`**Ticket:** [{KEY}] Title`) and
 * local-mode (`**Source:** / **Row:**`) plan headers, extracts
 * all plan sections, and maps to a synthetic `FetchedTicket`.
 */
import type { FetchedTicket } from '@chief-clancy/core';

import { createHash } from 'node:crypto';

// ─── Types ───────────────────────────────────────────────────────────────────

type ParsedPlan = {
  readonly key: string;
  readonly title: string;
  readonly summary: string;
  readonly affectedFiles: string;
  readonly approach: string;
  readonly testStrategy: string;
  readonly acceptance: string;
  readonly dependencies: string;
  readonly risks: string;
  readonly size: string;
  readonly planned: string;
  readonly headerFormat: 'board' | 'local';
};

type ApprovalStatus =
  | { readonly status: 'approved'; readonly approvedAt: string }
  | { readonly status: 'modified'; readonly approvedAt: string }
  | { readonly status: 'not-approved' };

export type ApprovalFs = {
  readonly readFile: (path: string) => string;
  readonly exists: (path: string) => boolean;
};

// ─── Helpers ─────────────────────────────────────────────────────────────────

const PLAN_HEADER = '## Clancy Implementation Plan';

/**
 * Extract the content between two `### Section` headings (or until EOF).
 *
 * Limitation: headings inside fenced code blocks are treated as section
 * boundaries. Plan files are machine-generated so this is not expected
 * in practice.
 */
function extractSection(content: string, heading: string): string {
  const pattern = new RegExp(`^### ${heading}\\s*$`, 'm');
  const match = pattern.exec(content);
  if (!match) return '';

  const start = match.index + match[0].length;
  const rest = content.slice(start);

  // Find next ### or ## heading (section boundary)
  const nextHeading = /^##+ /m.exec(rest);
  const raw = nextHeading ? rest.slice(0, nextHeading.index) : rest;

  // Strip the plan footer (generated-by line)
  return raw.replace(/^_Generated by \[Clancy\].*$/m, '').trim();
}

/** Extract size letter from "**S** — justification" or plain "S". */
function parseSize(raw: string): string {
  const match = /\*\*([SML])\*\*|^([SML])\b/m.exec(raw);
  return match?.[1] ?? match?.[2] ?? raw.trim();
}

// ─── parsePlanFile ───────────────────────────────────────────────────────────

/**
 * Parse a Clancy implementation plan file into structured fields.
 *
 * Supports both board-mode (`**Ticket:** [{KEY}] Title`) and local-mode
 * (`**Source:** / **Row:**`) header formats.
 *
 * @param content - Raw markdown content of the plan file.
 * @param slug - Plan slug used as the key in local-mode (e.g. `add-dark-mode-3`).
 * @returns Parsed plan with all sections extracted.
 */
export function parsePlanFile(content: string, slug: string): ParsedPlan {
  if (!content.includes(PLAN_HEADER)) {
    throw new Error(
      "Could not parse plan file. Expected '## Clancy Implementation Plan' header.",
    );
  }

  // Scope header detection to the block before the first ### section
  const firstSection = content.indexOf('\n### ');
  const headerBlock =
    firstSection >= 0 ? content.slice(0, firstSection) : content;

  // Detect header format from the header block only
  const ticketMatch = /^\*\*Ticket:\*\*\s*\[([^\]]+)\]\s*(.+)$/m.exec(
    headerBlock,
  );
  const headerFormat: 'board' | 'local' = ticketMatch ? 'board' : 'local';

  const { key, title } = ticketMatch
    ? { key: ticketMatch[1].trim(), title: ticketMatch[2].trim() }
    : {
        key: slug,
        title:
          /^\*\*Row:\*\*\s*#\d+\s*—\s*(.+)$/m.exec(headerBlock)?.[1]?.trim() ??
          slug,
      };

  const plannedMatch = /^\*\*Planned:\*\*\s*(.+)$/m.exec(headerBlock);
  const planned = plannedMatch ? plannedMatch[1].trim() : '';

  const sizeRaw = extractSection(content, 'Size Estimate');

  return {
    key,
    title,
    summary: extractSection(content, 'Summary'),
    affectedFiles: extractSection(content, 'Affected Files'),
    approach: extractSection(content, 'Implementation Approach'),
    testStrategy: extractSection(content, 'Test Strategy'),
    acceptance: extractSection(content, 'Acceptance Criteria'),
    dependencies: extractSection(content, 'Dependencies'),
    risks: extractSection(content, 'Risks / Considerations'),
    size: parseSize(sizeRaw),
    planned,
    headerFormat,
  };
}

// ─── checkApprovalStatus ─────────────────────────────────────────────────────

/**
 * Check the approval status of a plan file by reading its `.approved` marker.
 *
 * Derives the marker path by replacing the `.md` extension with `.approved`.
 *
 * @param planPath - Path to the plan `.md` file.
 * @param planContent - Current content of the plan file (for SHA comparison).
 * @param fs - Filesystem operations for reading the marker.
 * @returns Approval status: `approved` (SHA match), `modified` (SHA mismatch), or `not-approved` (no marker).
 */
export function checkApprovalStatus(
  planPath: string,
  planContent: string,
  fs: ApprovalFs,
): ApprovalStatus {
  const markerPath = planPath.replace(/\.md$/, '.approved');

  if (!fs.exists(markerPath)) {
    return { status: 'not-approved' };
  }

  const marker = fs.readFile(markerPath);
  const sha256Line = /^sha256=(.+)$/m.exec(marker);
  const approvedAtLine = /^approved_at=(.+)$/m.exec(marker);
  // Trim captures to handle CRLF line endings (Windows git checkouts)
  const approvedAt = approvedAtLine?.[1]?.trim() ?? '';

  const currentSha = createHash('sha256').update(planContent).digest('hex');
  const markerSha = sha256Line?.[1]?.trim() ?? '';

  if (currentSha === markerSha) {
    return { status: 'approved', approvedAt };
  }

  return { status: 'modified', approvedAt };
}

// ─── toSyntheticTicket ───────────────────────────────────────────────────────

/**
 * Map a parsed plan to a synthetic {@link FetchedTicket} for the pipeline.
 *
 * The description joins summary, affected files, approach, test strategy,
 * and acceptance criteria. Dependencies and risks are available on the
 * `ParsedPlan` for callers that need them separately.
 *
 * @param plan - Parsed plan to convert.
 * @returns Synthetic ticket with `parentInfo` and `blockers` set to `'none'`.
 */
export function toSyntheticTicket(plan: ParsedPlan): FetchedTicket {
  return {
    key: plan.key,
    title: plan.title,
    description: [
      plan.summary,
      plan.affectedFiles,
      plan.approach,
      plan.testStrategy,
      plan.acceptance,
    ].join('\n\n'),
    parentInfo: 'none',
    blockers: 'None',
  };
}
