import type { ApprovalFs } from './plan-file.js';
import type { FetchedTicket } from '@chief-clancy/core';

import { createHash } from 'node:crypto';

import fc from 'fast-check';
import { describe, expect, it, vi } from 'vitest';

import {
  checkApprovalStatus,
  parsePlanFile,
  toSyntheticTicket,
} from './plan-file.js';

// ─── Fixtures ────────────────────────────────────────────────────────────────

const BOARD_PLAN = `## Clancy Implementation Plan

**Ticket:** [PROJ-42] Add dark mode
**Planned:** 2026-04-13

### Summary

Enable system-wide dark mode toggle in settings.

### Affected Files

| File | Change Type | Description |
| --- | --- | --- |
| \`src/theme.ts\` | Modify | Add dark palette |

### Implementation Approach

Use CSS custom properties for theme switching.

### Test Strategy

- [ ] Verify toggle persists across sessions
- [ ] Verify contrast ratios meet WCAG AA

### Acceptance Criteria

- [ ] Dark mode toggle visible in settings
- [ ] System preference detected on first load

### Dependencies

None

### Risks / Considerations

- CSS variable fallback needed for older browsers

### Size Estimate

**M** — Moderate: theme system + toggle + persistence

---

_Generated by [Clancy](https://github.com/Pushedskydiver/chief-clancy). To request changes: comment on this ticket, then re-run \`/clancy:plan\` to revise._`;

const LOCAL_PLAN = `## Clancy Implementation Plan

**Source:** Add dark mode
**Brief:** 2026-04-13-add-dark-mode.md
**Row:** #3 — Enable system preference detection
**Planned:** 2026-04-13

### Summary

Detect OS-level dark mode preference on first load.

### Affected Files

| File | Change Type | Description |
| --- | --- | --- |
| \`src/hooks/useTheme.ts\` | Create | System preference hook |

### Implementation Approach

Use \`matchMedia('(prefers-color-scheme: dark)')\` with a listener for changes.

### Test Strategy

- [ ] Mock matchMedia in JSDOM

### Acceptance Criteria

- [ ] System preference applied on mount
- [ ] Preference changes reflected in real-time

### Dependencies

Depends on theme context from row #1.

### Risks / Considerations

- SSR mismatch if server renders light default

### Size Estimate

**S** — Small: single hook + listener`;

const MINIMAL_PLAN = `## Clancy Implementation Plan

**Ticket:** [ENG-7] Fix typo
**Planned:** 2026-04-13

### Summary

Fix typo in README.`;

const PLAN_WITH_FEEDBACK = `## Clancy Implementation Plan

**Source:** Refactor auth
**Brief:** 2026-04-10-refactor-auth.md
**Row:** #1 — Extract middleware
**Planned:** 2026-04-10

### Changes From Previous Plan

Addressed feedback about error handling.

### Summary

Extract auth middleware into standalone module.

### Affected Files

| File | Change Type | Description |
| --- | --- | --- |
| \`src/auth.ts\` | Modify | Extract middleware |

### Implementation Approach

Move middleware function and add error boundary.

### Test Strategy

- [ ] Unit test middleware isolation

### Acceptance Criteria

- [ ] Middleware works standalone

### Dependencies

None

### Risks / Considerations

- Import paths change for consumers

### Size Estimate

**S** — Small`;

const PLAN_WITH_FIGMA = `## Clancy Implementation Plan

**Ticket:** [PROJ-99] Add onboarding flow
**Planned:** 2026-04-13

### Summary

New user onboarding wizard.

### Affected Files

| File | Change Type | Description |
| --- | --- | --- |
| \`src/onboarding.tsx\` | Create | Wizard component |

### Implementation Approach

Multi-step form with validation.

### Test Strategy

- [ ] Step navigation works

### Acceptance Criteria

- [ ] All steps completable

### Dependencies

None

### Figma Link

https://www.figma.com/file/abc123/onboarding

### Risks / Considerations

- Long form may hurt mobile UX

### Size Estimate

**L** — Large: multi-step wizard`;

// ─── parsePlanFile ───────────────────────────────────────────────────────────

describe('parsePlanFile', () => {
  describe('board-mode header', () => {
    it('extracts key from [KEY] in Ticket line', () => {
      const plan = parsePlanFile(BOARD_PLAN, 'ignored-slug');
      expect(plan.key).toBe('PROJ-42');
    });

    it('extracts title from Ticket line', () => {
      const plan = parsePlanFile(BOARD_PLAN, 'ignored-slug');
      expect(plan.title).toBe('Add dark mode');
    });

    it('sets headerFormat to board', () => {
      const plan = parsePlanFile(BOARD_PLAN, 'ignored-slug');
      expect(plan.headerFormat).toBe('board');
    });
  });

  describe('local-mode header', () => {
    it('uses slug as key', () => {
      const plan = parsePlanFile(LOCAL_PLAN, 'add-dark-mode-3');
      expect(plan.key).toBe('add-dark-mode-3');
    });

    it('extracts title from Row line', () => {
      const plan = parsePlanFile(LOCAL_PLAN, 'add-dark-mode-3');
      expect(plan.title).toBe('Enable system preference detection');
    });

    it('sets headerFormat to local', () => {
      const plan = parsePlanFile(LOCAL_PLAN, 'add-dark-mode-3');
      expect(plan.headerFormat).toBe('local');
    });
  });

  describe('sections', () => {
    it('parses Summary', () => {
      const plan = parsePlanFile(BOARD_PLAN, 'x');
      expect(plan.summary).toBe(
        'Enable system-wide dark mode toggle in settings.',
      );
    });

    it('parses Affected Files table', () => {
      const plan = parsePlanFile(BOARD_PLAN, 'x');
      expect(plan.affectedFiles).toContain('`src/theme.ts`');
      expect(plan.affectedFiles).toContain('Add dark palette');
    });

    it('parses Implementation Approach', () => {
      const plan = parsePlanFile(BOARD_PLAN, 'x');
      expect(plan.approach).toBe(
        'Use CSS custom properties for theme switching.',
      );
    });

    it('parses Test Strategy', () => {
      const plan = parsePlanFile(BOARD_PLAN, 'x');
      expect(plan.testStrategy).toContain('toggle persists across sessions');
    });

    it('parses Acceptance Criteria', () => {
      const plan = parsePlanFile(BOARD_PLAN, 'x');
      expect(plan.acceptance).toContain('Dark mode toggle visible');
    });

    it('parses Dependencies', () => {
      const plan = parsePlanFile(BOARD_PLAN, 'x');
      expect(plan.dependencies).toBe('None');
    });

    it('parses Risks / Considerations', () => {
      const plan = parsePlanFile(BOARD_PLAN, 'x');
      expect(plan.risks).toContain('CSS variable fallback');
    });

    it('parses Size Estimate letter', () => {
      const plan = parsePlanFile(BOARD_PLAN, 'x');
      expect(plan.size).toBe('M');
    });

    it('parses Planned date', () => {
      const plan = parsePlanFile(BOARD_PLAN, 'x');
      expect(plan.planned).toBe('2026-04-13');
    });
  });

  describe('missing sections', () => {
    it('returns empty strings for absent sections', () => {
      const plan = parsePlanFile(MINIMAL_PLAN, 'fix-typo');
      expect(plan.affectedFiles).toBe('');
      expect(plan.approach).toBe('');
      expect(plan.testStrategy).toBe('');
      expect(plan.acceptance).toBe('');
      expect(plan.dependencies).toBe('');
      expect(plan.risks).toBe('');
    });

    it('still parses present sections', () => {
      const plan = parsePlanFile(MINIMAL_PLAN, 'fix-typo');
      expect(plan.summary).toBe('Fix typo in README.');
      expect(plan.key).toBe('ENG-7');
    });

    it('returns empty size when Size Estimate section absent', () => {
      const plan = parsePlanFile(MINIMAL_PLAN, 'fix-typo');
      expect(plan.size).toBe('');
    });
  });

  describe('malformed input', () => {
    it('throws on missing plan header', () => {
      expect(() => parsePlanFile('# Not a plan', 'x')).toThrow(
        "Could not parse plan file. Expected '## Clancy Implementation Plan' header.",
      );
    });

    it('throws on empty content', () => {
      expect(() => parsePlanFile('', 'x')).toThrow(
        '## Clancy Implementation Plan',
      );
    });

    it('falls back to slug when plan header present but no Ticket or Row', () => {
      const content =
        '## Clancy Implementation Plan\n\n### Summary\n\nSome content.';
      const plan = parsePlanFile(content, 'my-slug');
      expect(plan.headerFormat).toBe('local');
      expect(plan.key).toBe('my-slug');
      expect(plan.title).toBe('my-slug');
    });
  });

  describe('feedback / revision sections', () => {
    it('does not break parsing when Changes From Previous Plan present', () => {
      const plan = parsePlanFile(PLAN_WITH_FEEDBACK, 'refactor-auth-1');
      expect(plan.summary).toBe(
        'Extract auth middleware into standalone module.',
      );
      expect(plan.key).toBe('refactor-auth-1');
    });

    it('parses all standard sections alongside revision section', () => {
      const plan = parsePlanFile(PLAN_WITH_FEEDBACK, 'refactor-auth-1');
      expect(plan.approach).toContain('error boundary');
      expect(plan.acceptance).toContain('standalone');
    });
  });

  describe('optional Figma Link section', () => {
    it('parses Dependencies correctly when Figma Link follows', () => {
      const plan = parsePlanFile(PLAN_WITH_FIGMA, 'x');
      expect(plan.dependencies).toBe('None');
    });

    it('parses Risks correctly when Figma Link precedes it', () => {
      const plan = parsePlanFile(PLAN_WITH_FIGMA, 'x');
      expect(plan.risks).toContain('mobile UX');
    });

    it('parses Size correctly after Figma Link plan', () => {
      const plan = parsePlanFile(PLAN_WITH_FIGMA, 'x');
      expect(plan.size).toBe('L');
    });
  });

  describe('property-based', () => {
    it('never throws on valid plan with arbitrary section content', () => {
      fc.assert(
        fc.property(
          fc.record({
            summary: fc.string(),
            approach: fc.string(),
            deps: fc.string(),
          }),
          ({ summary, approach, deps }) => {
            const content = [
              '## Clancy Implementation Plan',
              '',
              '**Ticket:** [X-1] Test',
              '**Planned:** 2026-01-01',
              '',
              '### Summary',
              '',
              summary,
              '',
              '### Implementation Approach',
              '',
              approach,
              '',
              '### Dependencies',
              '',
              deps,
            ].join('\n');

            const plan = parsePlanFile(content, 'test');
            expect(plan.key).toBe('X-1');
            expect(typeof plan.summary).toBe('string');
            expect(typeof plan.approach).toBe('string');
            expect(typeof plan.dependencies).toBe('string');
          },
        ),
      );
    });

    it('always extracts slug as key in local mode', () => {
      fc.assert(
        fc.property(
          fc.string({ minLength: 1 }).filter((s) => !s.includes('\n')),
          (slug) => {
            const content = [
              '## Clancy Implementation Plan',
              '',
              '**Source:** test',
              `**Row:** #1 — Title`,
              '**Planned:** 2026-01-01',
            ].join('\n');

            const plan = parsePlanFile(content, slug);
            expect(plan.key).toBe(slug);
            expect(plan.headerFormat).toBe('local');
          },
        ),
      );
    });
  });
});

// ─── checkApprovalStatus ─────────────────────────────────────────────────────

describe('checkApprovalStatus', () => {
  const planContent = LOCAL_PLAN;
  const sha = createHash('sha256').update(planContent).digest('hex');

  function makeFs(overrides: Partial<ApprovalFs> = {}): ApprovalFs {
    return {
      readFile: vi.fn(() => ''),
      exists: vi.fn(() => false),
      ...overrides,
    };
  }

  it('returns not-approved when marker file missing', () => {
    const fs = makeFs({ exists: vi.fn(() => false) });
    const result = checkApprovalStatus('plans/x.md', planContent, fs);
    expect(result.status).toBe('not-approved');
  });

  it('returns approved when SHA matches', () => {
    const marker = `sha256=${sha}\napproved_at=2026-04-13T10:00:00Z\n`;
    const fs = makeFs({
      exists: vi.fn(() => true),
      readFile: vi.fn(() => marker),
    });
    const result = checkApprovalStatus('plans/x.md', planContent, fs);
    expect(result).toEqual({
      status: 'approved',
      approvedAt: '2026-04-13T10:00:00Z',
    });
  });

  it('returns modified when SHA does not match', () => {
    const marker = `sha256=0000000000000000000000000000000000000000000000000000000000000000\napproved_at=2026-04-13T09:00:00Z\n`;
    const fs = makeFs({
      exists: vi.fn(() => true),
      readFile: vi.fn(() => marker),
    });
    const result = checkApprovalStatus('plans/x.md', planContent, fs);
    expect(result).toEqual({
      status: 'modified',
      approvedAt: '2026-04-13T09:00:00Z',
    });
  });

  it('checks the .approved sibling path', () => {
    const existsFn = vi.fn(() => false);
    const fs = makeFs({ exists: existsFn });
    checkApprovalStatus('.clancy/plans/my-plan.md', planContent, fs);
    expect(existsFn).toHaveBeenCalledWith('.clancy/plans/my-plan.approved');
  });

  it('handles CRLF line endings in marker file', () => {
    const marker = `sha256=${sha}\r\napproved_at=2026-04-13T10:00:00Z\r\n`;
    const fs = makeFs({
      exists: vi.fn(() => true),
      readFile: vi.fn(() => marker),
    });
    const result = checkApprovalStatus('plans/x.md', planContent, fs);
    expect(result).toEqual({
      status: 'approved',
      approvedAt: '2026-04-13T10:00:00Z',
    });
  });
});

// ─── toSyntheticTicket ───────────────────────────────────────────────────────

describe('toSyntheticTicket', () => {
  it('maps key and title', () => {
    const plan = parsePlanFile(BOARD_PLAN, 'x');
    const ticket = toSyntheticTicket(plan);
    expect(ticket.key).toBe('PROJ-42');
    expect(ticket.title).toBe('Add dark mode');
  });

  it('joins plan sections into description', () => {
    const plan = parsePlanFile(BOARD_PLAN, 'x');
    const ticket = toSyntheticTicket(plan);
    expect(ticket.description).toContain(plan.summary);
    expect(ticket.description).toContain(plan.affectedFiles);
    expect(ticket.description).toContain(plan.approach);
    expect(ticket.description).toContain(plan.testStrategy);
    expect(ticket.description).toContain(plan.acceptance);
  });

  it('sets parentInfo and blockers to none', () => {
    const plan = parsePlanFile(BOARD_PLAN, 'x');
    const ticket = toSyntheticTicket(plan);
    expect(ticket.parentInfo).toBe('none');
    expect(ticket.blockers).toBe('none');
  });

  it('satisfies FetchedTicket type', () => {
    const plan = parsePlanFile(LOCAL_PLAN, 'add-dark-mode-3');
    const ticket: FetchedTicket = toSyntheticTicket(plan);
    expect(ticket.key).toBe('add-dark-mode-3');
  });
});
